In [1]:
import pandas as pd 
import numpy as np

In [6]:
with np.load("/Users/anshumaansoni/PycharmProjects/Molecular-Property-Prediction-Using-GNN-and-Transformer/Evaluation/Hybrid/predictions.npz", allow_pickle=True) as data:
    print(data.files)
    pred = pd.DataFrame(data["y_pred"])
    true = pd.DataFrame(data["y_true"])

['y_pred', 'y_true', 'smiles']

In [7]:
pred

,0,1,2,3,4,5,6,7,8,9,10,11
0,2.449490,80.322533,-0.241432,-0.007212,0.233412,1412.824585,0.172312,10863.469727,10861.179688,10862.182617,10869.305664,37.926491
1,3.127088,68.164421,-0.274489,-0.045124,0.228705,1176.512695,0.117141,11940.453125,11938.928711,11939.465820,11945.402344,32.804005
2,3.862666,70.648560,-0.262540,-0.000611,0.261275,1174.517944,0.130349,11708.642578,11707.137695,11707.592773,11713.955078,30.846916
3,1.424567,83.269661,-0.258298,0.060902,0.318299,1311.687256,0.196105,10122.566406,10120.694336,10121.153320,10129.478516,37.175518
4,0.203215,95.953354,-0.271368,0.095408,0.365433,1501.026733,0.257943,9320.180664,9318.938477,9318.424805,9329.620117,42.812630
...,...,...,...,...,...,...,...,...,...,...,...,...
11851,1.097664,85.849503,-0.232098,0.036242,0.267464,1333.737061,0.192851,9852.332031,9850.251953,9850.936523,9858.937500,35.841679
11852,0.774460,79.680389,-0.252807,0.065989,0.317634,1178.076416,0.191311,10806.514648,10805.119141,10805.147461,10813.686523,33.067535
11853,0.197111,66.908745,-0.221869,0.092777,0.314041,756.726074,0.152142,8104.565430,8103.212891,8103.459473,8110.112305,25.551754
11854,1.207242,84.544846,-0.240384,0.032847,0.272385,1368.450562,0.187732,10193.445312,10191.340820,10192.077148,10199.879883,35.428635
11855,0.604694,66.766708,-0.241395,0.050983,0.291698,702.734253,0.157837,7608.087891,7606.792969,7606.962891,7613.763672,25.202017

In [8]:
true

,0,1,2,3,4,5,6,7,8,9,10,11
0,3.9459,79.170006,-0.2321,-0.0849,0.1472,1220.620361,0.133291,10883.327148,10882.245117,10882.246094,10889.209961,35.085003
1,1.9347,62.470001,-0.3085,-0.0936,0.2149,1112.378174,0.063086,11780.840820,11780.142578,11780.143555,11784.997070,27.972000
2,5.7462,63.520004,-0.2788,-0.0352,0.2437,976.160400,0.090679,11806.834961,11806.006836,11806.007812,11811.573242,26.218000
3,1.6268,74.540001,-0.2589,0.0864,0.3453,1065.253418,0.176234,9066.041992,9064.765625,9064.766602,9072.664062,31.949001
4,0.1000,96.160004,-0.2608,0.0799,0.3407,1591.211548,0.250820,9160.248047,9158.524414,9158.525391,9168.990234,42.097000
...,...,...,...,...,...,...,...,...,...,...,...,...
11851,1.2736,87.920006,-0.2220,0.0212,0.2432,1246.910156,0.194809,9533.972656,9532.568359,9532.568359,9541.282227,34.933002
11852,1.4519,79.180000,-0.2362,0.0804,0.3166,878.373901,0.188938,10057.743164,10056.399414,10056.400391,10064.764648,27.317001
11853,1.0862,64.880005,-0.2101,0.0886,0.2987,644.905090,0.137621,7498.463867,7497.441406,7497.442383,7503.827148,22.966000
11854,1.6762,83.900002,-0.2340,0.0160,0.2499,1219.244507,0.184127,10057.787109,10056.446289,10056.447266,10064.805664,33.546001
11855,0.2213,67.810005,-0.2297,0.0237,0.2535,610.893127,0.151987,7072.592773,7071.505859,7071.506836,7078.232422,22.802000

In [12]:
diff = pred.iloc[:, 9] - true.iloc[:, 9]

In [13]:
diff

0         -20.063477
1         159.322266
2         -98.415039
3        1056.386719
4         159.899414
            ...
11851     318.368164
11852     748.747070
11853     606.017090
11854     135.629883
11855     535.456055
Name: 9, Length: 11856, dtype: float64